# Lesson 3 - Homework - Pandas and Numpy

### Hi again! :)

#### For today's homework, you will further explore the dataset recipe.csv. So start with importing the two key libraries: NumPy and pandas and loading the .csv file. Use the first column as index.

In [4]:
import pandas as pd
import numpy as np

In [21]:
df = pd.read_csv("data/recipes.csv")
df

Unnamed: 0  vegetarian  glutenFree  dairyFree  veryHealthy  healthScore  \
0             0        True        True       True        False          1.0   
1             1        True        True      False        False          0.0   
2             2       False       False      False        False          3.0   
3             3        True       False       True        False          2.0   
4             4       False        True      False        False         31.0   
..          ...         ...         ...        ...          ...          ...   
145         145       False        True       True        False         18.0   
146         146        True       False      False        False          1.0   
147         147        True        True       True         True         93.0   
148         148        True        True      False        False          5.0   
149         149        True        True       True         True        100.0   

     aggregateLikes      id  \
0                 3  633998   
1                 1  634426   
2                 1  635085   
3                 1  663229   
4                 3  651437   
..              ...     ...   
145              13  638315   
146               2  656248   
147               2  637297   
148               1  659412   
149               4  647875   

                                                 title  pricePerServing  ...  \
0                            Banana Blueberry Pancakes            55.79  ...   
1              Basil and Orange Confit Compound Butter            15.07  ...   
2                             Black Bottom Banana Bars            78.85  ...   
3                  The Best Raw Chocolate Chip Cookies            54.64  ...   
4                  Mediterranean Spinach Artichoke Dip           115.26  ...   
..                                                 ...              ...  ...   
145       Chicken Sausage, White Bean and Cabbage Soup           196.23  ...   
146                                Pinot Noir Brownies            65.76  ...   
147                          Cauliflower Chickpea Stew           139.28  ...   
148  Sautéed Balsamic Green Beans With Cherry Tomatoes           101.81  ...   
149        Indian-Style Dill and Turmeric Potato Salad           117.24  ...   

     VitaminB3Amount  VitaminB3percentOfDailyNeed VitaminB1Amount  \
0               0.49                         2.44            0.03   
1                NaN                          NaN             NaN   
2               2.63                        13.13            0.32   
3               0.65                         3.26            0.10   
4               0.66                         3.29            0.07   
..               ...                          ...             ...   
145             0.53                         2.67            0.15   
146             0.21                         1.07            0.03   
147             4.77                        23.83            0.45   
148             1.15                         5.73            0.12   
149             0.21                         1.05             NaN   

     VitaminB1percentOfDailyNeed  CalciumAmount  CalciumpercentOfDailyNeed  \
0                           2.26          18.11                       1.81   
1                            NaN            NaN                        NaN   
2                          21.09         100.80                      10.08   
3                           6.47          26.79                       2.68   
4                           4.64         162.84                      16.28   
..                           ...            ...                        ...   
145                        10.23         102.67                      10.27   
146                         1.68          19.82                       1.98   
147                        29.70         141.16                      14.12   
148                         7.85          55.64                       5.56   
149                    

#### Drop all the columns that are of Boolean type. We won't need them.

#### Keep the new dataframe stored in the same variable as the first one.

In [22]:
# df.dtypes
df = df.select_dtypes(exclude=['bool'])
df

Unnamed: 0  healthScore  aggregateLikes      id  \
0             0          1.0               3  633998   
1             1          0.0               1  634426   
2             2          3.0               1  635085   
3             3          2.0               1  663229   
4             4         31.0               3  651437   
..          ...          ...             ...     ...   
145         145         18.0              13  638315   
146         146          1.0               2  656248   
147         147         93.0               2  637297   
148         148          5.0               1  659412   
149         149        100.0               4  647875   

                                                 title  pricePerServing  \
0                            Banana Blueberry Pancakes            55.79   
1              Basil and Orange Confit Compound Butter            15.07   
2                             Black Bottom Banana Bars            78.85   
3                  The Best Raw Chocolate Chip Cookies            54.64   
4                  Mediterranean Spinach Artichoke Dip           115.26   
..                                                 ...              ...   
145       Chicken Sausage, White Bean and Cabbage Soup           196.23   
146                                Pinot Noir Brownies            65.76   
147                          Cauliflower Chickpea Stew           139.28   
148  Sautéed Balsamic Green Beans With Cherry Tomatoes           101.81   
149        Indian-Style Dill and Turmeric Potato Salad           117.24   

     readyInMinutes  servings  \
0                45         8   
1                45        10   
2                45         5   
3                45        12   
4                45         8   
..              ...       ...   
145              45         6   
146              45        16   
147              45         4   
148              45         4   
149              30         4   

                                             sourceUrl  CaloriesAmount  ...  \
0    https://www.foodista.com/recipe/K65SYB3F/banan...          175.67  ...   
1    https://www.foodista.com/recipe/ZCDX55YK/basil...           85.52  ...   
2    https://www.foodista.com/recipe/HPYY5YMF/black...          700.30  ...   
3    http://www.foodista.com/recipe/5K2BY4P7/the-be...          169.88  ...   
4    https://www.foodista.com/recipe/SWFHGWPH/medit...          144.42  ...   
..                                                 ...             ...  ...   
145  https://www.foodista.com/recipe/R66F23JJ/chick...          312.19  ...   
146  https://www.foodista.com/recipe/L5G2TX8B/pinot...          213.58  ...   
147  https://www.foodista.com/recipe/BQBJ3XVS/cauli...          455.50  ...   
148  https://www.foodista.com/recipe/Q33QTX2N/saute...           73.47  ...   
149  http://www.foodista.com/recipe/2LQW8RTQ/indian...          132.00  ...   

     VitaminB3Amount  VitaminB3percentOfDailyNeed  VitaminB1Amount  \
0               0.49                         2.44             0.03   
1                NaN                          NaN              NaN   
2               2.63                        13.13             0.32   
3               0.65                         3.26             0.10   
4               0.66                         3.29             0.07   
..               ...                          ...              ...   
145             0.53                         2.67             0.15   
146             0.21                         1.07             0.03   
147             4.77                        23.83             0.45   
148             1.15                         5.73             0.12   
149             0.21                         1.05              NaN   

     VitaminB1percentOfDailyNeed  CalciumAmount  CalciumpercentOfDailyNeed  \
0                           2.26          18.11                       1.81   
1                            NaN            NaN                        NaN   
2         

#### In some of the columns, there are less than 100 values available. Please drop them, too. We will learn how to deal with non-available values next time.

#### Keep the new dataframe stored in the same variable as the first one.

In [24]:
min_val = 100
df = df.dropna(axis=1, thresh=min_val)
df

Unnamed: 0  healthScore  aggregateLikes      id  \
0             0          1.0               3  633998   
1             1          0.0               1  634426   
2             2          3.0               1  635085   
3             3          2.0               1  663229   
4             4         31.0               3  651437   
..          ...          ...             ...     ...   
145         145         18.0              13  638315   
146         146          1.0               2  656248   
147         147         93.0               2  637297   
148         148          5.0               1  659412   
149         149        100.0               4  647875   

                                                 title  pricePerServing  \
0                            Banana Blueberry Pancakes            55.79   
1              Basil and Orange Confit Compound Butter            15.07   
2                             Black Bottom Banana Bars            78.85   
3                  The Best Raw Chocolate Chip Cookies            54.64   
4                  Mediterranean Spinach Artichoke Dip           115.26   
..                                                 ...              ...   
145       Chicken Sausage, White Bean and Cabbage Soup           196.23   
146                                Pinot Noir Brownies            65.76   
147                          Cauliflower Chickpea Stew           139.28   
148  Sautéed Balsamic Green Beans With Cherry Tomatoes           101.81   
149        Indian-Style Dill and Turmeric Potato Salad           117.24   

     readyInMinutes  servings  \
0                45         8   
1                45        10   
2                45         5   
3                45        12   
4                45         8   
..              ...       ...   
145              45         6   
146              45        16   
147              45         4   
148              45         4   
149              30         4   

                                             sourceUrl  CaloriesAmount  ...  \
0    https://www.foodista.com/recipe/K65SYB3F/banan...          175.67  ...   
1    https://www.foodista.com/recipe/ZCDX55YK/basil...           85.52  ...   
2    https://www.foodista.com/recipe/HPYY5YMF/black...          700.30  ...   
3    http://www.foodista.com/recipe/5K2BY4P7/the-be...          169.88  ...   
4    https://www.foodista.com/recipe/SWFHGWPH/medit...          144.42  ...   
..                                                 ...             ...  ...   
145  https://www.foodista.com/recipe/R66F23JJ/chick...          312.19  ...   
146  https://www.foodista.com/recipe/L5G2TX8B/pinot...          213.58  ...   
147  https://www.foodista.com/recipe/BQBJ3XVS/cauli...          455.50  ...   
148  https://www.foodista.com/recipe/Q33QTX2N/saute...           73.47  ...   
149  http://www.foodista.com/recipe/2LQW8RTQ/indian...          132.00  ...   

     ZincAmount  ZincpercentOfDailyNeed  VitaminEAmount  \
0          0.41                    2.71            0.40   
1           NaN                     NaN            0.33   
2          0.77                    5.12            0.69   
3           NaN                     NaN             NaN   
4          0.78                    5.21            1.15   
..          ...                     ...             ...   
145        1.08                    7.20            1.19   
146        0.69                    4.57            0.36   
147        2.64                   17.61            2.34   
148        0.39                    2.58            0.95   
149         NaN                     NaN            2.03   

     VitaminEpercentOfDailyNeed  VitaminB3Amount  VitaminB3percentOfDailyNeed  \
0                          2.70             0.49                         2.44   
1                          2.17              NaN                          NaN   
2                          4.61             2.63                        13.13   
3                           NaN             0.65    

#### Enough dropping. How big is your DataFrame now?

In [25]:
df.shape

(150, 67)

#### Too big. The columns are fine, but we will restrict ourselves to 50 recipes. Please choose any 50 recipes (hint: maybe the first 50? :) ).

#### Keep the new dataframe stored in the same variable as the first one.

In [26]:
df = df.head(50)
df

Unnamed: 0  healthScore  aggregateLikes       id  \
0            0          1.0               3   633998   
1            1          0.0               1   634426   
2            2          3.0               1   635085   
3            3          2.0               1   663229   
4            4         31.0               3   651437   
5            5         30.0               1  1096267   
6            6          5.0               1   647894   
7            7          0.0               1   982367   
8            8          4.0               1   641943   
9            9         62.0               1  1095768   
10          10         36.0              37   639606   
11          11          1.0               1   643877   
12          12          4.0               4   639209   
13          13          2.0               1   653353   
14          14         16.0               2   661036   
15          15          8.0               1   653399   
16          16         12.0               1   635793   
17          17         13.0               1   649882   
18          18          4.0               2   664533   
19          19          5.0               2   658126   
20          20         20.0               1   642892   
21          21         21.0              18   632874   
22          22         16.0               1   636600   
23          23          9.0               1   635447   
24          24          6.0               7   645416   
25          25          0.0               1   654516   
26          26         42.0               1   649225   
27          27         19.0               2   641962   
28          28          3.0               7   655145   
29          29         19.0               1   648742   
30          30         17.0               1  1096306   
31          31          5.0             249   716421   
32          32          6.0               1   652758   
33          33         54.0               2   641443   
34          34         78.0              15   661340   
35          35          9.0               6   634605   
36          36         57.0               1   647124   
37          37         17.0               1   658495   
38          38          9.0               1   649300   
39          39          7.0               6  1098357   
40          40         12.0               7   641904   
41          41          1.0               1   657875   
42          42          2.0               8   655098   
43          43         44.0               1   622825   
44          44          0.0               1  1095774   
45          45          2.0               0   715473   
46          46         49.0               1  1096242   
47          47          2.0              13   640827   
48          48         43.0               1   650126   
49          49          9.0               2   654953   

                                                title  pricePerServing  \
0                           Banana Blueberry Pancakes            55.79   
1             Basil and Orange Confit Compound Butter            15.07   
2                            Black Bottom Banana Bars            78.85   
3                 The Best Raw Chocolate Chip Cookies            54.64   
4                 Mediterranean Spinach Artichoke Dip           115.26   
5                            Turkey Burgers with Slaw           387.61   
6                      Individual Strawberry Souffles           101.40   
7                              Fidget Spinner Cookies            21.60   
8                             Easy Crawfish Jambalaya           126.04   
9   Bulgur Wheat Salad with Chickpeas, Bell Pepper...           229.28   
10                             Classic Greek Moussaka           441.50   
11                           Fromage Blanc Cheesecake           203.73   
12                               Chocolate Spelt Cake            74.24   
13          Nutella Cupcakes & Peanut Butter Frosting            59.65   
14                         Spicy Carr

#### Display only the columns referring to Fiber.

In [35]:
df.filter(axis=1, regex="Fiber*")


FiberAmount  FiberpercentOfDailyNeed
0          3.81                    15.22
1           NaN                      NaN
2          4.60                    18.40
3          3.45                    13.81
4          2.41                     9.64
5          2.95                    11.81
6          1.98                     7.94
7          1.56                     6.24
8          1.57                     6.27
9         27.10                   108.42
10        11.57                    46.28
11         1.54                     6.17
12         5.27                    21.07
13         2.57                    10.27
14         6.63                    26.53
15         4.52                    18.08
16          NaN                      NaN
17         3.19                    12.78
18         1.43                     5.71
19         1.78                     7.14
20         2.68                    10.71
21         1.09                     4.35
22         3.51                    14.03
23         0.68                     2.71
24         4.87                    19.49
25         1.72                     6.86
26         5.95                    23.82
27         6.96                    27.83
28         2.20                     8.79
29         3.12                    12.48
30        14.69                    58.75
31         4.34                    17.36
32         1.31                     5.23
33        11.79                    47.16
34         6.38                    25.51
35         1.14                     4.57
36         5.60                    22.39
37         5.79                    23.17
38         4.70                    18.81
39         1.71                     6.83
40         4.56                    18.23
41         0.81                     3.23
42         1.13                     4.50
43        12.40                    49.62
44         0.59                     2.36
45         0.91                     3.66
46         7.48                    29.91
47         1.37                     5.48
48         6.90                    27.59
49         1.92                     7.67

#### And now the columns referring to Fiber for recipes from rows numbered 10 to 30.

In [33]:
df[10:31].filter(regex="Fiber*")

FiberAmount  FiberpercentOfDailyNeed
10        11.57                    46.28
11         1.54                     6.17
12         5.27                    21.07
13         2.57                    10.27
14         6.63                    26.53
15         4.52                    18.08
16          NaN                      NaN
17         3.19                    12.78
18         1.43                     5.71
19         1.78                     7.14
20         2.68                    10.71
21         1.09                     4.35
22         3.51                    14.03
23         0.68                     2.71
24         4.87                    19.49
25         1.72                     6.86
26         5.95                    23.82
27         6.96                    27.83
28         2.20                     8.79
29         3.12                    12.48
30        14.69                    58.75

#### Cool. Now choose your favourite recipe and display only the respective row in the DataFrame.

In [47]:
df[df["title"] == "Mussels Marinara"]


Unnamed: 0  healthScore  aggregateLikes      id             title  \
32          32          6.0               1  652758  Mussels Marinara   

    pricePerServing  readyInMinutes  servings  \
32            125.9              45         4   

                                            sourceUrl  CaloriesAmount  ...  \
32  http://www.foodista.com/recipe/CTFS3HVP/mussel...           78.59  ...   

    ZincAmount  ZincpercentOfDailyNeed  VitaminEAmount  \
32        0.39                    2.57            0.77   

    VitaminEpercentOfDailyNeed  VitaminB3Amount  VitaminB3percentOfDailyNeed  \
32                        5.16              0.9                         4.52   

    VitaminB1Amount  VitaminB1percentOfDailyNeed  CalciumAmount  \
32             0.06                         4.19          41.74   

    CalciumpercentOfDailyNeed  
32                       4.17  

[1 rows x 67 columns]

#### And now the columns referring to Fiber FOR your favourite recipe.

In [48]:
df[df["title"] == "Mussels Marinara"].filter(regex="Fiber")

FiberAmount  FiberpercentOfDailyNeed
32         1.31                     5.23

#### One last thing. What is the difference between accessing the column "vegetarian" in those two ways:
- df["vegetarian"]
- df[["vegetarian"]]

#### (df is the name of your DataFrame).

Hint: what are the types of these two?

## Please remember that difference.

In [59]:
df["FiberAmount"].dtype
# df[["FiberAmount"]].dtype

dtype('float64')

# Exercises on Numpy

1. Write a NumPy program to create an array of the integers from 10 to 50

In [24]:

arr1 = np.arange(10,51)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

2. And print the Even and odd integers from the above array

In [39]:
arr_even = []
arr_odd = []
for x in arr1:
    if x%2 == 0:
        arr_even.append(x)
    else:
        arr_odd.append(x)
print("even numbers:")
print(arr_even)
print("odd numbers:")
print(arr_odd)


even numbers:
[10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]
odd numbers:
[11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49]


3. Write a NumPy program to convert an array to a float type. 

__Expected output__:

Original array
[1, 2, 3, 4]

Array converted to a float type:
[ 1. 2. 3. 4.]

In [40]:
a = np.array([1,2,3,4], dtype='float')
a

array([1., 2., 3., 4.])

4. Create a 2X2 integer array and print it's values and then print max along the axis 1 of that result.


In [47]:
a1 = np.array([[1,2], [3,4]])
print(a1)
print(np.argmax(a1,axis=1))

[[1 2]
 [3 4]]
[1 1]


5. Create a 2-d array named ints and perform the following operations

- Print second row of ints

- Print all elements of ints that are greater than six

- Double every element of ints

- Replace the third column of ints

In [57]:
ints = np.array([[1,2,3,4], [5,6,7,8]])
# second row of ints
print(ints[1])
# all elements of ints that is greater than 6
print(ints[ints>6])
# Double every element of ints
print(ints*2)
# Replace the third column of ints
ints[:,2] = 0
print(ints)

[5 6 7 8]
[7 8]
[[ 2  4  6  8]
 [10 12 14 16]]
[[1 2 0 4]
 [5 6 0 8]]


## #See you!!1